# onshape server url
onshape_server: https://cad.onshape.com/api/v17
# document to download files from
document_id: 0979ae98021520f5b9b15ec4
# id of the boolean property which marks which parts
# should be exported
export_property_id: 6ac858725613576ec52ea4e7
# use default workspace
use_default_workspace: true
# use a specific workspace/version/microversion
# only if use_default workspace is false,
workspace_id: ""
# if specified ID is a workspace (w), version (v),
# or microversion (m). For example, if you have
# provided a workspace, you would do
# 
# workspace_type: "w"
workspace_type: ""  
